version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - database

  database:
    container_name: database  
    image: 'postgres:12.1-alpine'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres: